### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by garykw** [georgeOsdDev/react-dropfile-field#12]
when I input the key
import DropfileField from 'react-dropfile-field' for my application, my builder ran into the following issue.

ERROR in ./~/react-dropfile-field/index.js
Module parse failed: ./~/node_modules/react-dropfile-field/index.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import DropfileField from './lib/components/DropfileField';
| export default DropfileField;
|
 @ ./src/components/pages/support.jsx 67:30-61

**Comment by georgeOsdDev** [comment]
@garywong89 
I have fixed index.js and released v0.0.5.
Please try new version.
Thanks!
